-- CreateTable
CREATE TABLE "users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "name" STRING NOT NULL,
    "hashed_password" STRING NOT NULL,
    "is_active" BOOL NOT NULL DEFAULT true,
    "role" STRING NOT NULL DEFAULT 'user',

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sensor_readings" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "mode" STRING NOT NULL,
    "temperature" FLOAT8 NOT NULL,
    "pressure" FLOAT8 NOT NULL,
    "flow_rate" FLOAT8 NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sensor_readings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "predictions" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sensor_id" INT4 NOT NULL,
    "hydrate_risk" FLOAT8 NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "predictions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_knowledge_posts" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "source_id" STRING,
    "source_type" STRING,
    "source_name" STRING,
    "source_url" STRING,
    "title" STRING NOT NULL,
    "original_content" STRING,
    "summary" STRING,
    "key_insights" STRING,
    "practical_takeaways" STRING,
    "why_it_matters" STRING,
    "content_type" STRING,
    "tags" STRING,
    "relevance_score" FLOAT8 NOT NULL DEFAULT 0.0,
    "credibility_score" FLOAT8 NOT NULL DEFAULT 0.0,
    "author" STRING,
    "published_at" TIMESTAMP(3),
    "fetched_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processed_at" TIMESTAMP(3),
    "is_published" BOOL NOT NULL DEFAULT false,
    "is_featured" BOOL NOT NULL DEFAULT false,
    "view_count" INT4 NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_knowledge_posts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "feed_sources" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "source_type" STRING NOT NULL,
    "url" STRING NOT NULL,
    "is_active" BOOL NOT NULL DEFAULT true,
    "fetch_interval_hours" INT4 NOT NULL DEFAULT 24,
    "last_fetched_at" TIMESTAMP(3),
    "credibility_weight" FLOAT8 NOT NULL DEFAULT 0.5,
    "config" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "feed_sources_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "feed_fetch_logs" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "source_id" INT4,
    "source_name" STRING,
    "started_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMP(3),
    "status" STRING,
    "items_fetched" INT4 NOT NULL DEFAULT 0,
    "items_processed" INT4 NOT NULL DEFAULT 0,
    "items_published" INT4 NOT NULL DEFAULT 0,
    "error_message" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "feed_fetch_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "ai_knowledge_posts_source_id_key" ON "ai_knowledge_posts"("source_id");

-- CreateIndex
CREATE UNIQUE INDEX "feed_sources_name_key" ON "feed_sources"("name");

-- AddForeignKey
ALTER TABLE "predictions" ADD CONSTRAINT "predictions_sensor_id_fkey" FOREIGN KEY ("sensor_id") REFERENCES "sensor_readings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

